refactor: Remove Timber library from library module
Removed Timber library from the library module because:
1. it's causing crash on android 7.1 with this crash stacktrace
java.lang.NoClassDefFoundError: Failed resolution of: Timber/log/Timber.
2. the library should not include a logging library dependency in order
to be a light weight library with minimum size effect on the app size
that include it as possible.